// angular2/src/app/components/loading/loading.component.ts
import { Component } from '@angular/core';
import { Subscription } from 'rxjs';

import { SubjectProvider } from '../../providers/subject.provider';


@Component({
    selector: 'loading-component',
    templateUrl: './loading.component.html',
    styleUrls: ['./loading.component.css']
})
export class LoadingComponent {

    state = { queues: [] }

    subscription: Subscription;

    constructor(private subject: SubjectProvider) {
    }

    ngOnInit() {
        this.subscription = this.subject.observable('app.components.loading.queues').subscribe(
            queue => {
                if (queue.type == 'push') {
                    this.state.queues.push(queue);
                } else if (queue.type == 'pop') {
                    this.state.queues.pop();
                } else {
                    throw 'undefined type: ' + queue.type;
                }
            }
        )
    }

    ngOnDestroy() {
        this.subscription.unsubscribe();
    }
}
<div class="xs-loading" [ngStyle]="{'display': state.queues.length > 0 ? 'block' : 'none'}">
    {{state.queues.length > 0 ? state.queues[state.queues.length - 1].message : ''}}
</div>

// react/src/components/loading/loading.component.jsx
import React from 'react';

import Icon from 'antd/lib/icon';
import 'antd/lib/icon/style/css';

import * as config from '../../config';
import { observable } from '../../providers/subject.provider';

import './loading.component.scss';


export default class LoadingComponent extends React.Component {

    state = { queues: [] }

    componentWillMount() {
        this.subscription = observable(this.props.observable).subscribe(status => {
            if (status.type == 'push') {
                this.state.queues.push(status);
            } else if (status.type == 'pop') {
                this.state.queues.pop();
            } else {
                throw 'undefined type: ' + status.type;
            }
            this.setState({ queues: this.state.queues });
        });
    }

    componentWillUnmount() {
        this.subscription && this.subscription.unsubscribe();
    }

    render() {
        let message = this.state.queues.length > 0 ? this.state.queues[this.state.queues.length - 1].message || config.components.loading.message : config.components.loading.message;
        return (
            <div className={'bc-loading' + (this.state.queues.length > 0 ? ' bc-block' : ' bc-hide')}>
                <div className="bc-icon">
                    <Icon type="loading" title={message} />
                    {message}
                </div>
            </div>
        )
    }
}
